// routes.go — routes extracted to per-entity packages under domain/treasury/<entity>/.
// This file is intentionally left as a placeholder; the facade (treasury.go) will
// re-export entity-local types when generated by the finalize agent.
package treasury
